### ISSUE TITLE
Issue with velero-notifications

### ISSUE THREAD

**Issue by egulpen2** [vitobotta/velero-notifications#1]
Hi!

First of all, thanks for the release!
I have a issue, when i run a manual backup it seems to be working. But my scheduled backups are not generating any notifications.

Any idea why?

Thanks!

**Comment by vitobotta** [comment]
Hi, unfortunately I haven't really used this tool myself for a while now, as I switched to monitoring and alerts with Grafana. I am not sure what the problem could be. I will set the project as archived since it's no longer maintained. Sorry!

**Comment by jkanczler** [comment]
@vitobotta and if you're not using this anymore as you've mentioned, you're using Grafana. How you're using Grafana to detect velero-notification successes or failures?

**Comment by vitobotta** [comment]
Hi @jkanczler - actually I am maintaining this project again and I updated it 4 days ago. I am still using Grafana but I just prefer what I did with this project (straight notifications to slack/email/webhook), so I picked it up again :)
